version: "3.2"

services:
    nginx:
        build: ./nginx
        volumes:
            - static_files:/user/src/app/static/
        ports:
            - "801:80"
        depends_on:
            - backend
        restart: "on-failure"

    app:
        image: "jc21/nginx-proxy-manager:latest"
        restart: unless-stopped
        ports:
            - "80:80"
            - "81:81"
            - "443:443"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt

    backend:
        command: sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --no-input &&
            gunicorn main_website.wsgi:application --bind 0.0.0.0:8000"
        build:
            context: ./server/
            dockerfile: Dockerfile
        volumes:
            - static_files:/user/src/app/static/
            - ./server/db.sqlite3:/user/src/app/db.sqlite3

        env_file:
            - ./server/.env

volumes:
    static_files:
