# Generated by Django 4.0.5 on 2023-03-05 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_offline_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
