# Generated by Django 4.0.5 on 2023-03-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ieee_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ieee_member_id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_rules',
            field=models.TextField(null=True),
        ),
    ]
