# Generated by Django 4.0.5 on 2023-03-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_order_user_order_player_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='event_id',
            new_name='event',
        ),
    ]
