# Generated by Django 4.0.5 on 2023-03-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_event_id_order_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='players',
        ),
    ]
