# Generated by Django 4.0.5 on 2023-03-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_user_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='player_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_verified',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('PO', 'Pending'), ('CO', 'Completed')], default='PO', max_length=20),
        ),
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ManyToManyField(to='user.event'),
        ),
    ]
