# Generated by Django 4.0.5 on 2023-03-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_order_event_order_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ManyToManyField(to='user.event'),
        ),
    ]
