# Generated by Django 4.0.5 on 2023-03-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_event_group_size_alter_event_group_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ManyToManyField(to='user.event'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.event'),
        ),
    ]
