# Generated by Django 4.0.5 on 2023-03-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_structure',
            field=models.TextField(null=True),
        ),
    ]
