# Generated by Django 4.0.5 on 2023-04-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_event_event_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.event'),
        ),
    ]
