# Generated by Django 4.0.5 on 2023-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
