# Generated by Django 4.0.5 on 2023-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(default='000000', max_length=8),
        ),
    ]
