# Generated by Django 4.0.5 on 2023-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_taker',
            field=models.CharField(default='online', max_length=40),
        ),
    ]
