# Generated by Django 4.0.5 on 2023-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_order_order_taker'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_taker',
            field=models.CharField(default='online', max_length=40),
        ),
    ]
