# Generated by Django 4.0.5 on 2023-04-20 10:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_transaction_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(default=user.models.generate_team_id, max_length=6, unique=True),
        ),
    ]
