# Generated by Django 4.0.5 on 2023-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
