# Generated by Django 4.0.5 on 2023-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_img',
            field=models.URLField(blank=True),
        ),
    ]
