# Generated by Django 4.0.5 on 2023-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_order_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_co',
            field=models.URLField(default='www.credenz.in'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_po',
            field=models.URLField(default='www.credenz.in'),
        ),
    ]
