# Generated by Django 4.0.5 on 2023-04-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_event_event_co_event_event_po'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event_img',
        ),
    ]
