# Generated by Django 4.0.5 on 2023-05-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_user_phone'),
        ('user', '0041_remove_order_event_img'),
    ]

    operations = [
    ]
