# Generated by Django 4.0.5 on 2023-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_merge_20230430_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_password',
            field=models.CharField(default='pass', max_length=8),
        ),
    ]
