# Generated by Django 4.0.5 on 2023-05-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_team_team_password'),
        ('user', '0043_user_has_purchased_pass'),
    ]

    operations = [
    ]
