# Generated by Django 4.0.5 on 2023-05-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_merge_20230501_1949'),
        ('user', '0046_alter_team_event'),
    ]

    operations = [
    ]
