# Generated by Django 4.0.5 on 2023-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_merge_0044_merge_20230501_1949_0046_alter_team_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_password',
            field=models.CharField(default='pass', max_length=8, null=True),
        ),
    ]
