# Generated by Django 4.0.5 on 2023-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_alter_team_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment',
            field=models.CharField(choices=[('PO', 'Pending'), ('CO', 'Completed'), ('IO', 'Invalid')], default='PO', max_length=20, null=True),
        ),
    ]
